In [ ]:
 import numpy as np
arr =np.array([10,20,30,40,50])

print("Array:",arr)
print("Shape:", arr.shape)
print("Size:",arr.size)
print("Data type", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type int64


In [ ]:
import numpy as np
arr =np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

zeros = np.zeros((3, 4))
ones = np.ones((3, 4))
identity = np.eye(4)
print(zeros)
print(ones)
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
even_number = np.arange(10,50,2)
print(even_number)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
import numpy as np
arr =np.linspace(0 ,1, 10)
print( arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
import numpy as np
a = np.array([20,30,40,50,60])
b = np.array([10,15,20,25,30])
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Addition: [30 45 60 75 90]
Substraction: [10 15 20 25 30]
Multiplication: [ 200  450  800 1250 1800]
Division: [2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
arr = np.array([13,14,15,16])
print("Square:",arr**2)
print("Cube:",arr**3)

Square: [169 196 225 256]
Cube: [2197 2744 3375 4096]


In [ ]:
import numpy as np
arr = np.array([100,200,300,400])
arr1 =arr*1.15
print(arr1)

[115. 230. 345. 460.]


In [ ]:
import numpy as np
a = np.array([10, 25, 30, 45])
b = np.array([15, 20, 35, 40])
print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [15 25 35 45]
Minimum: [10 20 30 40]


In [ ]:
import numpy as np
arr =np.arange(21)
print("first five elements:",arr[:5])
print("last five elemrnt:",arr[])

first five elements: [0 1 2 3 4]


In [ ]:
arr = np.arange(21)
print("Array:", arr)

print("First five elements:", arr[:5])
print("Last five elements:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

NameError: name 'np' is not defined

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr[:5] = 100
print(arr)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

view = arr[1:4]
copy = arr[1:4].copy()

view[0] = 99
copy[1] = 88

print("Original:", arr)
print("View:", view)
print("Copy:", copy)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[::-1])

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])

In [ ]:
print(arr[:2, 1:])

In [ ]:
arr = np.arange(1, 26).reshape(5, 5)

print("First row:", arr[0])
print("Last column:", arr[:, -1])
print("Middle element:", arr[2, 2])
print("Top-left 3x3:")
print(arr[:3, :3])

In [ ]:
arr = np.arange(1, 13)

print(arr.reshape(3, 4))

In [ ]:
arr = np.arange(1, 11)

print(arr.reshape(2, 5))

In [ ]:
arr = np.arange(1, 13).reshape(3, 4)

print(arr.T)

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)

print("Transpose:")
print(arr.transpose(2, 1, 0))

print("Swapaxes:")
print(arr.swapaxes(0, 2))

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Addition:")
print(a + b)

print("Multiplication:")
print(a * b)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))

In [ ]:
a = np.array([[1, 2], [3, 4]])

transpose = a.T

print("Transpose:")
print(transpose)

print("Dot product:")
print(np.dot(transpose, a))

In [ ]:
arr = np.array([4, 9, 16, 25])

print(np.sqrt(arr))

In [ ]:
arr = np.array([1, 2, 3])

print(np.exp(arr))

In [ ]:
arr = np.random.randn(5)

print("Array:", arr)
print("Square root:", np.sqrt(np.abs(arr)))
print("Exponential:", np.exp(arr))
print("Absolute:", np.abs(arr))

In [ ]:
a = np.random.rand(5)
b = np.random.rand(5)

print(np.maximum(a, b))

In [ ]:
marks = np.array([35, 72, 48, 90, 55, 28])

result = np.where(marks < 40, 0, marks)

print(result)

In [ ]:
income = np.array([30000, 60000, 45000, 80000, 55000])

result = np.where(income >= 50000, "High", "Low")

print(result)

In [ ]:
arr = np.array([10, 35, 20, 45, 30, 50])

result = np.where(arr > 30, 100, arr)

print(result)

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Variance:", np.var(arr))
print("Standard deviation:", np.std(arr))

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Row-wise:", np.sum(arr, axis=1))
print("Column-wise:", np.sum(arr, axis=0))

In [ ]:
marks = np.array([45, 67, 89, 56, 72, 90, 34, 78, 65, 50])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

In [ ]:
arr = np.array([True, True, False])

print("Any:", np.any(arr))
print("All:", np.all(arr))

In [ ]:
arr = np.random.randint(1, 100, 10)

print("Original:", arr)
print("Sorted:", np.sort(arr))

In [ ]:
arr = np.array([10, 20, 10, 30, 20, 40, 30])

print(np.unique(arr))

In [ ]:
marks = np.array([50, 60, 50, 70, 80, 60, 90])

print(np.unique(marks))

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
values = np.array([20, 60, 40])

print(np.in1d(values, arr))

In [ ]:
marks = np.array([
    [60, 70, 80],
    [40, 50, 45],
    [80, 90, 85],
    [30, 40, 35],
    [70, 75, 80],
    [55, 60, 65],
    [90, 85, 95],
    [45, 50, 55],
    [65, 70, 60],
    [50, 55, 60]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("Total:", total)
print("Average:", average)

print("Students with average >= 50:")
print(np.where(average >= 50)[0])

In [ ]:
arr = np.arange(1, 17).reshape(4, 4)

print("Transpose:")
print(arr.T)

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

print("Central 2x2:")
print(arr[1:3, 1:3])

In [ ]:
arr = np.random.randn(20)

print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Sorted:", np.sort(arr))

result = np.where(arr < 0, 0, arr)

print("Negative values replaced:")
print(result)

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

addition = a + b
multiplication = a * b
matrix_product = np.dot(a, b)

print("Addition:")
print(addition)

print("Element-wise multiplication:")
print(multiplication)

print("Matrix multiplication:")
print(matrix_product)

print("Transpose of A:")
print(a.T)

print("Maximum:")
print(np.maximum(a, b))

print("Minimum:")
print(np.minimum(a, b))

In [ ]:
arr = np.arange(1, 25).reshape(4, 6)

print("Original:")
print(arr)

print("Selected rows:")
print(arr[[0, 2]])

print("Selected columns:")
print(arr[:, [1, 3, 5]])

print("Transpose:")
print(arr.T)

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))

print("Row mean:", np.mean(arr, axis=1))
print("Column mean:", np.mean(arr, axis=0))

print("Unique values:")
print(np.unique(arr))